### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by olemah** [sparks-alec/QSpotify#5]
I love this script, but it seems it is not possible to use a playlist URI to play a playlist. Or am I missing something?

**Comment by sparks-alec** [comment]
hmmm, looks like maybe Spotify changed the syntax of the URI they supply for playlists. this is a bug!

**Comment by sparks-alec** [comment]
fixed! Spotify used to prefix spotify:playlist URI's with spotify:user. They don't do that anymore, which broke playlist functionality. Thanks for letting me know!
